
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sc3RvcmFnZTpsaXN0LHVzZXI6ZGVsLGRpY3Q6YWRkLGRlcHQ6bGlzdCx0aW1pbmc6YWRkLGRpY3Q6ZGVsLGRpY3Q6bGlzdCx0aW1pbmc6bGlzdCxyb2xlczphZGQsdXNlcjphZGQscGljdHVyZXM6bGlzdCxzdHVkZW50Omxpc3QsbWVudTplZGl0LHRpbWluZzplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxyb2xlczpsaXN0LHBpY3R1cmVzOmRlbCxzaWduOmxpc3QsY291cnNlOmxzaXQsbWVudTphZGQscGljdHVyZXM6YWRkLHVzZXI6ZWRpdCxyb2xlczplZGl0LHRpbWluZzpkZWwsZGljdDplZGl0LGRlcHQ6ZGVsIiwiZXhwIjoxNTg5NDI4MDczfQ.ftALWXenBsvOjNRi4tMbaKc5qbUkYi4GC8M_yKgrCWuohGg20tflsYleNgI5dCdrBCk0wVVmYlKI-k7tgCz5Jg

POST http://localhost:8000/mobile/login HTTP/1.1
content-type: application/json

{
  "username": "zhengjie@tom.com",
  "password": "123456",
  "role": "student"
}

###

POST http://localhost:8000/api/code/validated
content-type: application/json

{
  "code": "405169",
  "type": "email",
  "scenes": "重置密码",
  "value": "460678244@qq.com"
}

###

Get http://localhost:8000/api/userSysVal?userId=1
Authorization:{{token}}

###


POST http://localhost:8000/api/userSysVal
content-type: application/json
Authorization:{{token}}

{
  "sysVal": { "id": 2 },
  "userId": 1,
  "value": 102
}


###

POST http://localhost:8000/api/student/register
content-type: application/json
Authorization:{{token}}

{
  "college": { "id": 8 },
  "email": "910079546@qq.com",
  "password": "123456",
  "name": "熊乾程",
  "phone": "15688165559",
  "sex": "男",
  "studentNumber": "190327084"
}

###

Get http://localhost:8000/api/course
Authorization:{{token}}

###

Get http://localhost:8000/api/course/test?id=3

###

Get http://localhost:8000/api/studentCourseSign/sign?id=1


###

Get http://localhost:8000/api/signHistory
Authorization:{{token}}

###

Get http://localhost:8000/api/users?size=10&page=0&sort=id
Authorization:{{token}}

###

PUT  http://localhost:8000/api/studentCourseSign/sign
content-type: application/json
Authorization:{{token}}

[2]

###

PUT  http://localhost:8000/api/course
content-type: application/json
Authorization:{{token}}

{
  "id": 4,
  "courseName":"wdcd",
  "courseCode":"1234521",
  "college": {"id": 7}
}

###

DELETE   http://localhost:8000/api/course
content-type: application/json
Authorization:{{token}}

{
  "id
}