POST http://localhost:8000/auth/login HTTP/1.1
content-type: application/json

{
  "username":"wdc",
  "password":"123456"
}

###

POST http://localhost:8000/api/code/validated
content-type: application/json

{
  "code": "405169",
  "type": "email",
  "scenes": "重置密码",
  "value": "460678244@qq.com"
}

###

Get http://localhost:8000/api/code/test
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sc3RvcmFnZTpsaXN0LGRlcGxveUhpc3Rvcnk6bGlzdCx1c2VyOmRlbCxkaWN0OmFkZCxkZXB0Omxpc3QsdGltaW5nOmFkZCxkaWN0OmRlbCxkaWN0Omxpc3QsYXBwOmxpc3QsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxyb2xlczphZGQsdXNlcjphZGQscGljdHVyZXM6bGlzdCxtZW51OmVkaXQsdGltaW5nOmVkaXQsbWVudTpsaXN0LHN0b3JhZ2U6ZGVsLHJvbGVzOmxpc3QscGljdHVyZXM6ZGVsLGNvdXJzZTpsc2l0LG1lbnU6YWRkLHBpY3R1cmVzOmFkZCx1c2VyOmVkaXQscm9sZXM6ZWRpdCx0aW1pbmc6ZGVsLGRpY3Q6ZWRpdCxzZXJ2ZXJEZXBsb3k6bGlzdCxkZXB0OmRlbCIsImV4cCI6MTU4ODI3MTIzMn0.LL9WSVe1Jvdb3LjVsslu14vkW3HobjYIvjnwZEedT4cU7LLSfqi0at_2Sr8IT-auRVeKS-h7Qn8n7fPa6smF7A

###

Get http://localhost:8000/api/users?size=10&page=0&sort=id
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sam9iOmVkaXQsZGVwbG95SGlzdG9yeTpsaXN0LHVzZXI6ZGVsLGRpY3Q6YWRkLGRlcHQ6bGlzdCx0aW1pbmc6YWRkLGpvYjpsaXN0LGRpY3Q6ZGVsLGRpY3Q6bGlzdCxhcHA6bGlzdCxqb2I6YWRkLGRhdGFiYXNlOmxpc3QsZGVwbG95Omxpc3Qscm9sZXM6YWRkLHVzZXI6YWRkLG1lbnU6ZWRpdCx0aW1pbmc6ZWRpdCxtZW51Omxpc3Qsc3RvcmFnZTpkZWwscm9sZXM6bGlzdCxjb3Vyc2U6bHNpdCxtZW51OmFkZCxqb2I6ZGVsLHVzZXI6ZWRpdCxyb2xlczplZGl0LHRpbWluZzpkZWwsZGljdDplZGl0LHNlcnZlckRlcGxveTpsaXN0LGRlcHQ6ZGVsIiwiZXhwIjoxNTg3ODE0NTgwfQ.GLVxRdxzdSMjSrhNVc4zjL3PGnUF-HfegsbDqEaNl13W8ZuSHL5YLmNlN3lMFwbMGI3Pgor8At_sUaRDXKJOBw

###

POST http://localhost:8000/api/course
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sc3RvcmFnZTpsaXN0LGRlcGxveUhpc3Rvcnk6bGlzdCx1c2VyOmRlbCxkaWN0OmFkZCxkZXB0Omxpc3QsdGltaW5nOmFkZCxkaWN0OmRlbCxkaWN0Omxpc3QsYXBwOmxpc3QsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxyb2xlczphZGQsdXNlcjphZGQscGljdHVyZXM6bGlzdCxtZW51OmVkaXQsdGltaW5nOmVkaXQsbWVudTpsaXN0LHN0b3JhZ2U6ZGVsLHJvbGVzOmxpc3QscGljdHVyZXM6ZGVsLGNvdXJzZTpsc2l0LG1lbnU6YWRkLHBpY3R1cmVzOmFkZCx1c2VyOmVkaXQscm9sZXM6ZWRpdCx0aW1pbmc6ZGVsLGRpY3Q6ZWRpdCxzZXJ2ZXJEZXBsb3k6bGlzdCxkZXB0OmRlbCIsImV4cCI6MTU4ODMxNzM5M30.DPAbsKZHG0PMCwnxGntyx2L2MFkAm-U9Ff5nf2WucJr5H4PhUUqAn7SZV1SLFfCrHd_i_P8_Z3esiSrLV7EdTg

{
  "courseName":"wdc",
  "courseCode":"123459",
  "college": {"id": 7}
}

###

PUT  http://localhost:8000/api/course
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sZGVwbG95SGlzdG9yeTpsaXN0LHVzZXI6ZGVsLGRpY3Q6YWRkLGRlcHQ6bGlzdCx0aW1pbmc6YWRkLGRpY3Q6ZGVsLGRpY3Q6bGlzdCxhcHA6bGlzdCxkYXRhYmFzZTpsaXN0LGRlcGxveTpsaXN0LHJvbGVzOmFkZCx1c2VyOmFkZCxtZW51OmVkaXQsdGltaW5nOmVkaXQsbWVudTpsaXN0LHN0b3JhZ2U6ZGVsLHJvbGVzOmxpc3QsbWVudTphZGQsY291cnNlOmxzaXQsdXNlcjplZGl0LHJvbGVzOmVkaXQsdGltaW5nOmRlbCxkaWN0OmVkaXQsc2VydmVyRGVwbG95Omxpc3QsZGVwdDpkZWwiLCJleHAiOjE1ODc4MzA1MjZ9.gs2e7wSQxGzOjgbqyykkwTZXxralbNpEpCzli7Ug-914dPKSr2rZJcDGV0rBmzCwJ_JMD58VTNit6R7rSRVN4A

{
  "id": 4,
  "courseName":"wdcd",
  "courseCode":"1234521",
  "college": {"id": 7}
}

###

DELETE   http://localhost:8000/api/course
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sam9iOmVkaXQsZGVwbG95SGlzdG9yeTpsaXN0LHVzZXI6ZGVsLGRpY3Q6YWRkLGRlcHQ6bGlzdCx0aW1pbmc6YWRkLGpvYjpsaXN0LGRpY3Q6ZGVsLGRpY3Q6bGlzdCxhcHA6bGlzdCxqb2I6YWRkLGRhdGFiYXNlOmxpc3QsZGVwbG95Omxpc3Qscm9sZXM6YWRkLHVzZXI6YWRkLG1lbnU6ZWRpdCx0aW1pbmc6ZWRpdCxtZW51Omxpc3Qsc3RvcmFnZTpkZWwscm9sZXM6bGlzdCxjb3Vyc2U6bHNpdCxtZW51OmFkZCxqb2I6ZGVsLHVzZXI6ZWRpdCxyb2xlczplZGl0LHRpbWluZzpkZWwsZGljdDplZGl0LHNlcnZlckRlcGxveTpsaXN0LGRlcHQ6ZGVsIiwiZXhwIjoxNTg3ODE0NTgwfQ.GLVxRdxzdSMjSrhNVc4zjL3PGnUF-HfegsbDqEaNl13W8ZuSHL5YLmNlN3lMFwbMGI3Pgor8At_sUaRDXKJOBw

{
  "id
}