
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsdXNlcjpsaXN0LHN0b3JhZ2U6YWRkLHN0dWRlbnQ6ZGVsLGRlcHQ6YWRkLHN0b3JhZ2U6ZWRpdCxtZW51OmRlbCxyb2xlczpkZWwsYWRtaW4sc2lnbjpkZWwsc3RvcmFnZTpsaXN0LGRlcGxveUhpc3Rvcnk6bGlzdCx1c2VyOmRlbCxkaWN0OmFkZCxkZXB0Omxpc3QsdGltaW5nOmFkZCxkaWN0OmRlbCxkaWN0Omxpc3QsYXBwOmxpc3QsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxjb3Vyc2U6bGlzdCxyb2xlczphZGQsdXNlcjphZGQscGljdHVyZXM6bGlzdCxzdHVkZW50Omxpc3Qsc3R1ZGVudDphZGQsbWVudTplZGl0LHRpbWluZzplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxyb2xlczpsaXN0LHBpY3R1cmVzOmRlbCxzaWduOmxpc3QsbWVudTphZGQscGljdHVyZXM6YWRkLHVzZXI6ZWRpdCxyb2xlczplZGl0LHN0dWRlbnQ6ZWRpdCx0aW1pbmc6ZGVsLGRpY3Q6ZWRpdCxzZXJ2ZXJEZXBsb3k6bGlzdCxkZXB0OmRlbCIsImV4cCI6MTU4ODkyMTI4M30.vcC6nNKiq9XzoWUU6SKYIsR8w9p9-qSub8Ou2fl7I-wcP6E8UbXBDgC9tsitVICdeWJ7gm_q2lTpJ9NtQRtOuw

POST http://localhost:8000/auth/login HTTP/1.1
content-type: application/json

{
  "username":"wdc",
  "password":"123456"
}

###

POST http://localhost:8000/api/code/validated
content-type: application/json

{
  "code": "405169",
  "type": "email",
  "scenes": "重置密码",
  "value": "460678244@qq.com"
}

###

Get http://localhost:8000/api/course
Authorization:{{token}}

###

Get http://localhost:8000/api/course/test?id=3

###

Get http://localhost:8000/api/studentCourseSign/sign?id=1


###

Get http://localhost:8000/api/signHistory
Authorization:{{token}}

###

Get http://localhost:8000/api/users?size=10&page=0&sort=id
Authorization:{{token}}

###

PUT  http://localhost:8000/api/studentCourseSign/sign
content-type: application/json
Authorization:{{token}}

[2]

###

PUT  http://localhost:8000/api/course
content-type: application/json
Authorization:{{token}}

{
  "id": 4,
  "courseName":"wdcd",
  "courseCode":"1234521",
  "college": {"id": 7}
}

###

DELETE   http://localhost:8000/api/course
content-type: application/json
Authorization:{{token}}

{
  "id
}